# Generated by Django 5.0.6 on 2024-07-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='id',
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_reserva',
            field=models.AutoField(db_column='idreserva', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
